import type { Metadata } from "next";
import { notoSansJp } from '@/app/components/ui/fonts'
import "@/app/globals.css";
import Header from "@/app/components/ui/Header/Header";
import Footer from "@/app/components/ui/Footer/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={notoSansJp.variable}>
      <body className="min-h-screen">
      <Header />
          {children}
     <Footer/>
      </body>
    </html>
  );
}
